# Generated by Django 6.0.7 on 2026-09-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed')], default='SUBMITTED', max_length=20),
        ),
    ]
