# Generated by Django 6.0.7 on 2026-08-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('CLOTHING', 'Clothing'), ('GROCERY', 'Grocery'), ('FURNITURE', 'Furniture'), ('OTHERS', 'Others')], max_length=20),
        ),
    ]
