# Generated by Django 6.0.7 on 2026-08-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='quality',
            new_name='quantity',
        ),
    ]
