# Generated by Django 6.0.7 on 2026-08-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_quality_sale_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(),
        ),
    ]
